version: "3.8"

services:
  web-app:
    container_name: springboot-native-demo-0
    image: springboot-native-demo:latest
    build:
      context: .
      dockerfile: docker/Dockerfile-native
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:4001"