FROM maven:3.9.6-eclipse-temurin-21 as builder

WORKDIR /build/app
ADD . /build/app
RUN mvn clean package -P jvm -DskipTests

FROM eclipse-temurin:21-jdk
COPY --from=builder /build/app/target/springboot-jvm.jar /opt

# docker build -t springboot-jvm:latest -f docker/Dockerfile-jvm .
# docker run --name springboot-jvm-1 -e 'PORT=8083' -p 8083:8083 springboot-jvm:latest java -jar ./opt/springboot-jvm.jar

