FROM gianlucamori/graalvm-compiler:java21 as builder

WORKDIR /build/app
ADD . /build/app
RUN mvn clean package -P native -DskipTests

FROM debian:bookworm-slim
COPY --from=builder /build/app/target/springboot-native.out /opt

# docker build -t springboot-native:latest -f docker/Dockerfile-native .
# docker run --name springboot-native-1 -e 'PORT=8082' -p 8082:8082 springboot-native:latest ./opt/springboot-native.out