FROM gianlucamori/graalvm-compiler:java17-graal22.3.1 as builder

WORKDIR /build/app
ADD . /build/app
RUN mvn clean package -P native -DskipTests

FROM gcr.io/distroless/base-debian11
COPY --from=builder /build/app/target/springboot-native.out /

# docker build -t springboot-native:latest -f docker/Dockerfile-native .
# docker run --name springboot-native-1 -e 'PORT=8082' -p 8082:8082 -d springboot-native:latest ./springboot-native.out